window.MINDSET_CONTENT = {
  "en": [
    "Change Your Thinking, Change Your Life",
    "A Journey of Thought, Awareness, and Purpose",
    "A person’s real life begins on the day they take responsibility for their own thinking.",
    "You Were Not Born Merely to Survive",
    "You were not brought into this world only to earn a living, please others, or simply endure difficult days.",
    "There is a deeper potential within you—waiting to be discovered, developed, and shared. You can learn. You can change. You can create. You can make another person’s life a little better.",
    "Your age is not the end of your story. It is evidence of your experience, your wisdom, and the strength you have gathered along the way.",
    "Every Morning Is a New Decision",
    "You do not have to remain the person you were yesterday.",
    "Each morning offers you two choices:",
    "Repeat the thinking that has held you back;",
    "Or give your life a new direction.",
    "Change rarely happens in a single day. But one honest decision, made on one particular day, can change the direction of an entire life.",
    "Fear Is Not Your Enemy",
    "Fear often stands outside the very door behind which your growth is waiting.",
    "Fear does not always mean, “Stop.”",
    "Sometimes it means:",
    "You are stepping beyond the boundaries you once believed were permanent.",
    "Take one small step. Then take another.",
    "Confidence does not always come before action. Very often, confidence is born because you acted despite being afraid.",
    "Learning Has No Age",
    "The moment a person stops learning, something within them begins to stand still.",
    "A new language, a new skill, a new technology, or a new way of seeing the world keeps the mind alive.",
    "Ask yourself each day:",
    "What can I understand today that I did not understand yesterday?",
    "Knowledge becomes powerful when it leaves the mind and enters life through action.",
    "Turn Your Pain into Strength",
    "The difficult experiences of your life did not come only to break you. They also helped shape your depth, your wisdom, and your strength.",
    "A person who has known pain can understand others more gently. A person who has faced hardship knows the true value of patience.",
    "Do not be ashamed of your story.",
    "Perhaps the chapter you wish to hide will one day become the light that helps someone else continue.",
    "Purpose Is Not Found—It Is Built",
    "The purpose of life does not always arrive as a clear answer from the sky.",
    "It begins to take shape when you:",
    "Solve a problem;",
    "Help another person;",
    "Develop your abilities;",
    "Share what you have learned;",
    "Bring honesty, meaning, and care into your work.",
    "The simple principle is this:",
    "Use what you are learning to create value for someone beyond yourself.",
    "Your Worth Is Greater Than Your Income",
    "Your worth is greater than your salary, your qualifications, or your social position.",
    "Your true value lives in your intentions, your character, your experience, your compassion, and the good you bring into the lives of others.",
    "Money is important, but money can never tell the whole story of a human being.",
    "Consistency Is Stronger Than Motivation",
    "Motivation comes and goes.",
    "Consistency says:",
    "I will not wait for the perfect mood. I will take a step towards the life I believe in.",
    "Give even one hour each day to your future.",
    "The step may be small. The progress may be quiet. But small actions, repeated with patience, can create a life that once seemed impossible.",
    "Protect Your Mind",
    "The things you watch, hear, read, and repeat become part of the world inside you.",
    "Do not give every negative voice a home in your mind.",
    "Speak to yourself with the same kindness you would offer to someone you love:",
    "I can learn.",
    "I can begin again.",
    "There is still potential within me.",
    "The next chapter of my life is still mine to write.",
    "Your Next Chapter Has Not Been Written Yet",
    "Your past mistakes are not your final verdict.",
    "The present is the place where your future is being built.",
    "Today, you may be a learner. Tomorrow, you may become a creator. One day, you may become a teacher whose experience gives courage to others.",
    "The most beautiful part of life is often the part that has not arrived yet.",
    "A Final Message",
    "Do not spend your whole life trying to make everything perfect.",
    "Try to make it meaningful.",
    "Learn something every day. Help someone whenever you can. Protect your health, your mind, and your inner peace. Remain honest before your Creator, your conscience, and the purpose placed within you.",
    "You are not too late.",
    "You are not finished.",
    "You are still becoming.",
    "And as long as a person is willing to learn, their story is still alive.",
    "A Journey of Growth, Purpose, and Inner Awakening",
    "Learn → Understand → Act → Share → Grow → Become a Light",
    "AI-generated content by Muhammad Naveed Ishaque"
  ],
  "ur": [
    "سوچ بدلو، زندگی بدل دو",
    "سوچ، شعور اور زندگی کے اصول",
    "انسان کی اصل زندگی اُس دن شروع ہوتی ہے جب وہ اپنی سوچ کی ذمہ داری خود قبول کر لیتا ہے۔",
    "تم صرف زندہ رہنے کے لیے پیدا نہیں ہوئے",
    "تم اس دنیا میں صرف روزی کمانے، لوگوں کو خوش کرنے یا مشکل دن گزارنے کے لیے نہیں آئے۔",
    "تمہارے اندر ایسی صلاحیتیں موجود ہیں جو ابھی پوری طرح ظاہر نہیں ہوئیں۔ تم سیکھ سکتے ہو، بدل سکتے ہو، تخلیق کر سکتے ہو اور کسی دوسرے انسان کی زندگی بہتر بنا سکتے ہو۔",
    "تمہاری عمر تمہاری کہانی کا اختتام نہیں؛ یہ تمہارے تجربے، شعور اور پختگی کا ثبوت ہے۔",
    "ہر صبح ایک نیا فیصلہ ہے",
    "کل تم جو تھے، آج وہی رہنا ضروری نہیں۔",
    "ہر صبح تمہارے سامنے دو راستے ہوتے ہیں:",
    "پرانی سوچ کو دہراتے رہو؛",
    "یا اپنی زندگی کو نئی سمت دو۔",
    "تبدیلی ایک ہی دن میں نہیں آتی، لیکن ایک دن کیا گیا درست فیصلہ پوری زندگی بدل سکتا ہے۔",
    "خوف تمہارا دشمن نہیں",
    "خوف اکثر اُس دروازے کے باہر کھڑا ہوتا ہے جس کے اندر تمہاری ترقی چھپی ہوتی ہے۔",
    "خوف کا مطلب ہمیشہ یہ نہیں ہوتا کہ رک جاؤ۔ کبھی کبھی خوف کا مطلب ہوتا ہے:",
    "تم اپنی پرانی حدود سے باہر نکل رہے ہو۔",
    "ایک چھوٹا قدم اٹھاؤ، پھر دوسرا۔ خود اعتمادی عمل کے بعد پیدا ہوتی ہے، عمل سے پہلے نہیں۔",
    "سیکھنا عمر کا پابند نہیں",
    "جو انسان سیکھنا چھوڑ دیتا ہے، وہ اندر سے رک جاتا ہے۔",
    "نئی زبان، نئی مہارت، نئی ٹیکنالوجی اور نئی سوچ انسان کے ذہن کو زندہ رکھتے ہیں۔",
    "ہر روز اپنے آپ سے پوچھو:",
    "آج میں کل سے بہتر کیا سمجھ سکتا ہوں؟",
    "علم اُس وقت طاقت بنتا ہے جب وہ عمل میں تبدیل ہو جائے۔",
    "اپنی تکلیف کو اپنی طاقت بناؤ",
    "زندگی کے مشکل تجربات تمہیں توڑنے کے لیے نہیں آئے۔ انہوں نے تمہیں گہرا، سمجھدار اور مضبوط بنانے میں حصہ لیا ہے۔",
    "جو انسان درد کو سمجھتا ہے، وہ دوسروں کو بہتر سمجھ سکتا ہے۔ جو انسان مشکلات سے گزرا ہو، وہ صبر کی قدر جانتا ہے۔",
    "اپنی کہانی سے شرمندہ مت ہو۔ ممکن ہے تمہاری کہانی کسی دوسرے انسان کے لیے روشنی بن جائے۔",
    "مقصد ملتا نہیں، بنایا جاتا ہے",
    "زندگی کا مقصد ہمیشہ آسمان سے کسی واضح جواب کی صورت میں نہیں اترتا۔",
    "مقصد اُس وقت پیدا ہوتا ہے جب تم:",
    "کسی مسئلے کو حل کرتے ہو؛",
    "کسی انسان کی مدد کرتے ہو؛",
    "اپنی صلاحیت کو ترقی دیتے ہو؛",
    "اپنا علم دوسروں تک پہنچاتے ہو؛",
    "اپنے کام میں دیانت اور معنی پیدا کرتے ہو۔",
    "مقصد کا آسان اصول یہ ہے:",
    "جو کچھ تم سیکھ رہے ہو، اسے کسی کے فائدے کے لیے استعمال کرو۔",
    "تمہاری قدر صرف آمدنی نہیں",
    "تمہاری قدر تمہاری تنخواہ، ڈگری یا معاشرتی حیثیت سے کہیں زیادہ ہے۔",
    "تمہاری اصل قدر تمہاری نیت، کردار، تجربے، ہمدردی اور خدمت میں ہے۔",
    "دولت ضروری ہے، لیکن دولت انسان کا مکمل تعارف نہیں ہوتی۔",
    "پابندی، جوش سے زیادہ طاقتور ہے",
    "جوش کبھی ہوتا ہے اور کبھی نہیں ہوتا۔",
    "پابندی کا مطلب ہے:",
    "میں اپنے مزاج کا انتظار نہیں کروں گا؛ میں اپنے مقصد کی طرف قدم بڑھاؤں گا۔",
    "ہر روز صرف ایک گھنٹہ اپنے مستقبل کو دو۔ کام چھوٹا ہو، لیکن مسلسل ہو۔ مسلسل چھوٹے قدم بڑی تبدیلی پیدا کرتے ہیں۔",
    "اپنی سوچ کی حفاظت کرو",
    "جو چیزیں تم روز دیکھتے، سنتے اور پڑھتے ہو، وہ تمہاری سوچ کی تعمیر کرتی ہیں۔",
    "ہر منفی آواز کو اپنے اندر گھر مت دو۔",
    "اپنے آپ سے ایسے بات کرو جیسے تم کسی عزیز دوست سے بات کرتے ہو:",
    "میں سیکھ سکتا ہوں۔",
    "میں دوبارہ آغاز کر سکتا ہوں۔",
    "میرے اندر اب بھی صلاحیت موجود ہے۔",
    "میری زندگی کا اگلا باب میرے اختیار میں ہے۔",
    "تمہاری اگلی منزل ابھی لکھی نہیں گئی",
    "تمہاری سابقہ غلطیاں آخری فیصلہ نہیں ہیں۔",
    "تمہارا حال ایک ایسی جگہ ہے جہاں تم اپنے مستقبل کی تعمیر کر رہے ہو۔",
    "آج تم سیکھنے والے ہو سکتے ہو، کل تعمیر کرنے والے، اور آنے والے وقت میں استاد۔",
    "زندگی کا سب سے خوبصورت حصہ اکثر وہ ہوتا ہے جو ابھی آنا باقی ہوتا ہے۔",
    "آخری پیغام",
    "اپنی زندگی کو کامل بنانے کی کوشش مت کرو؛ اسے بامقصد بناؤ۔",
    "ہر روز کچھ سیکھو۔ کسی کی مدد کرو۔ اپنی صحت اور سوچ کا خیال رکھو۔ اپنے رب، اپنے ضمیر اور اپنے مقصد کے سامنے سچے رہو۔",
    "تم دیر سے نہیں آئے۔",
    "تم ختم نہیں ہوئے۔",
    "تم ابھی بھی تشکیل پا رہے ہو۔",
    "اور جب تک انسان سیکھ رہا ہے، اُس کی کہانی زندہ ہے۔",
    "ہر انسان کے لیے ترقی، مقصد اور باطن کی بیداری کا سفر",
    "سیکھو → سمجھو → عمل کرو → بانٹو → ترقی کرو → روشنی بنو",
    "مصنوعی ذہانت سے تخلیق کردہ مواد — محمد نوید اسحاق"
  ]
};
