window.MINDSET_CONTENT = {
  "en": [
    "Change Your Thinking, Change Your Life",
    "A Journey of Thought, Awareness, and Purpose",
    "A person’s real life begins on the day they take responsibility for their own thinking.",
    "You Were Not Born Merely to Survive",
    "You were not brought into this world only to earn a living, please others, or simply endure difficult days.",
    "There is a deeper potential within you—waiting to be discovered, developed, and shared. You can learn. You can change. You can create. You can make another person’s life a little better.",
    "Your age is not the end of your story. It is evidence of your experience, your wisdom, and the strength you have gathered along the way.",
    "Every Morning Is a New Decision",
    "You do not have to remain the person you were yesterday.",
    "Each morning offers you two choices:",
    "Repeat the thinking that has held you back;",
    "Or give your life a new direction.",
    "Change rarely happens in a single day. But one honest decision, made on one particular day, can change the direction of an entire life.",
    "Fear Is Not Your Enemy",
    "Fear often stands outside the very door behind which your growth is waiting.",
    "Fear does not always mean, “Stop.”",
    "Sometimes it means:",
    "You are stepping beyond the boundaries you once believed were permanent.",
    "Take one small step. Then take another.",
    "Confidence does not always come before action. Very often, confidence is born because you acted despite being afraid.",
    "Learning Has No Age",
    "The moment a person stops learning, something within them begins to stand still.",
    "A new language, a new skill, a new technology, or a new way of seeing the world keeps the mind alive.",
    "Ask yourself each day:",
    "What can I understand today that I did not understand yesterday?",
    "Knowledge becomes powerful when it leaves the mind and enters life through action.",
    "Turn Your Pain into Strength",
    "The difficult experiences of your life did not come only to break you. They also helped shape your depth, your wisdom, and your strength.",
    "A person who has known pain can understand others more gently. A person who has faced hardship knows the true value of patience.",
    "Do not be ashamed of your story.",
    "Perhaps the chapter you wish to hide will one day become the light that helps someone else continue.",
    "Purpose Is Not Found—It Is Built",
    "The purpose of life does not always arrive as a clear answer from the sky.",
    "It begins to take shape when you:",
    "Solve a problem;",
    "Help another person;",
    "Develop your abilities;",
    "Share what you have learned;",
    "Bring honesty, meaning, and care into your work.",
    "The simple principle is this:",
    "Use what you are learning to create value for someone beyond yourself.",
    "Your Worth Is Greater Than Your Income",
    "Your worth is greater than your salary, your qualifications, or your social position.",
    "Your true value lives in your intentions, your character, your experience, your compassion, and the good you bring into the lives of others.",
    "Money is important, but money can never tell the whole story of a human being.",
    "Consistency Is Stronger Than Motivation",
    "Motivation comes and goes.",
    "Consistency says:",
    "I will not wait for the perfect mood. I will take a step towards the life I believe in.",
    "Give even one hour each day to your future.",
    "The step may be small. The progress may be quiet. But small actions, repeated with patience, can create a life that once seemed impossible.",
    "Protect Your Mind",
    "The things you watch, hear, read, and repeat become part of the world inside you.",
    "Do not give every negative voice a home in your mind.",
    "Speak to yourself with the same kindness you would offer to someone you love:",
    "I can learn.",
    "I can begin again.",
    "There is still potential within me.",
    "The next chapter of my life is still mine to write.",
    "Your Next Chapter Has Not Been Written Yet",
    "Your past mistakes are not your final verdict.",
    "The present is the place where your future is being built.",
    "Today, you may be a learner. Tomorrow, you may become a creator. One day, you may become a teacher whose experience gives courage to others.",
    "The most beautiful part of life is often the part that has not arrived yet.",
    "A Final Message",
    "Do not spend your whole life trying to make everything perfect.",
    "Try to make it meaningful.",
    "Learn something every day. Help someone whenever you can. Protect your health, your mind, and your inner peace. Remain honest before your Creator, your conscience, and the purpose placed within you.",
    "You are not too late.",
    "You are not finished.",
    "You are still becoming.",
    "And as long as a person is willing to learn, their story is still alive.",
    "A Journey of Growth, Purpose, and Inner Awakening",
    "Learn → Understand → Act → Share → Grow → Become a Light",
    "AI-generated content by Muhammad Naveed Ishaque"
  ],
  "ur": [
    "سوچ بدلو، زندگی بدل دو",
    "سوچ، شعور اور زندگی کے اصول",
    "انسان کی اصل زندگی اُس دن شروع ہوتی ہے جب وہ اپنی سوچ کی ذمہ داری خود قبول کر لیتا ہے۔",
    "تم صرف زندہ رہنے کے لیے پیدا نہیں ہوئے",
    "تم اس دنیا میں صرف روزی کمانے، لوگوں کو خوش کرنے یا مشکل دن گزارنے کے لیے نہیں آئے۔",
    "تمہارے اندر ایسی صلاحیتیں موجود ہیں جو ابھی پوری طرح ظاہر نہیں ہوئیں۔ تم سیکھ سکتے ہو، بدل سکتے ہو، تخلیق کر سکتے ہو اور کسی دوسرے انسان کی زندگی بہتر بنا سکتے ہو۔",
    "تمہاری عمر تمہاری کہانی کا اختتام نہیں؛ یہ تمہارے تجربے، شعور اور پختگی کا ثبوت ہے۔",
    "ہر صبح ایک نیا فیصلہ ہے",
    "کل تم جو تھے، آج وہی رہنا ضروری نہیں۔",
    "ہر صبح تمہارے سامنے دو راستے ہوتے ہیں:",
    "پرانی سوچ کو دہراتے رہو؛",
    "یا اپنی زندگی کو نئی سمت دو۔",
    "تبدیلی ایک ہی دن میں نہیں آتی، لیکن ایک دن کیا گیا درست فیصلہ پوری زندگی بدل سکتا ہے۔",
    "خوف تمہارا دشمن نہیں",
    "خوف اکثر اُس دروازے کے باہر کھڑا ہوتا ہے جس کے اندر تمہاری ترقی چھپی ہوتی ہے۔",
    "خوف کا مطلب ہمیشہ یہ نہیں ہوتا کہ رک جاؤ۔ کبھی کبھی خوف کا مطلب ہوتا ہے:",
    "تم اپنی پرانی حدود سے باہر نکل رہے ہو۔",
    "ایک چھوٹا قدم اٹھاؤ، پھر دوسرا۔ خود اعتمادی عمل کے بعد پیدا ہوتی ہے، عمل سے پہلے نہیں۔",
    "سیکھنا عمر کا پابند نہیں",
    "جو انسان سیکھنا چھوڑ دیتا ہے، وہ اندر سے رک جاتا ہے۔",
    "نئی زبان، نئی مہارت، نئی ٹیکنالوجی اور نئی سوچ انسان کے ذہن کو زندہ رکھتے ہیں۔",
    "ہر روز اپنے آپ سے پوچھو:",
    "آج میں کل سے بہتر کیا سمجھ سکتا ہوں؟",
    "علم اُس وقت طاقت بنتا ہے جب وہ عمل میں تبدیل ہو جائے۔",
    "اپنی تکلیف کو اپنی طاقت بناؤ",
    "زندگی کے مشکل تجربات تمہیں توڑنے کے لیے نہیں آئے۔ انہوں نے تمہیں گہرا، سمجھدار اور مضبوط بنانے میں حصہ لیا ہے۔",
    "جو انسان درد کو سمجھتا ہے، وہ دوسروں کو بہتر سمجھ سکتا ہے۔ جو انسان مشکلات سے گزرا ہو، وہ صبر کی قدر جانتا ہے۔",
    "اپنی کہانی سے شرمندہ مت ہو۔ ممکن ہے تمہاری کہانی کسی دوسرے انسان کے لیے روشنی بن جائے۔",
    "مقصد ملتا نہیں، بنایا جاتا ہے",
    "زندگی کا مقصد ہمیشہ آسمان سے کسی واضح جواب کی صورت میں نہیں اترتا۔",
    "مقصد اُس وقت پیدا ہوتا ہے جب تم:",
    "کسی مسئلے کو حل کرتے ہو؛",
    "کسی انسان کی مدد کرتے ہو؛",
    "اپنی صلاحیت کو ترقی دیتے ہو؛",
    "اپنا علم دوسروں تک پہنچاتے ہو؛",
    "اپنے کام میں دیانت اور معنی پیدا کرتے ہو۔",
    "مقصد کا آسان اصول یہ ہے:",
    "جو کچھ تم سیکھ رہے ہو، اسے کسی کے فائدے کے لیے استعمال کرو۔",
    "تمہاری قدر صرف آمدنی نہیں",
    "تمہاری قدر تمہاری تنخواہ، ڈگری یا معاشرتی حیثیت سے کہیں زیادہ ہے۔",
    "تمہاری اصل قدر تمہاری نیت، کردار، تجربے، ہمدردی اور خدمت میں ہے۔",
    "دولت ضروری ہے، لیکن دولت انسان کا مکمل تعارف نہیں ہوتی۔",
    "پابندی، جوش سے زیادہ طاقتور ہے",
    "جوش کبھی ہوتا ہے اور کبھی نہیں ہوتا۔",
    "پابندی کا مطلب ہے:",
    "میں اپنے مزاج کا انتظار نہیں کروں گا؛ میں اپنے مقصد کی طرف قدم بڑھاؤں گا۔",
    "ہر روز صرف ایک گھنٹہ اپنے مستقبل کو دو۔ کام چھوٹا ہو، لیکن مسلسل ہو۔ مسلسل چھوٹے قدم بڑی تبدیلی پیدا کرتے ہیں۔",
    "اپنی سوچ کی حفاظت کرو",
    "جو چیزیں تم روز دیکھتے، سنتے اور پڑھتے ہو، وہ تمہاری سوچ کی تعمیر کرتی ہیں۔",
    "ہر منفی آواز کو اپنے اندر گھر مت دو۔",
    "اپنے آپ سے ایسے بات کرو جیسے تم کسی عزیز دوست سے بات کرتے ہو:",
    "میں سیکھ سکتا ہوں۔",
    "میں دوبارہ آغاز کر سکتا ہوں۔",
    "میرے اندر اب بھی صلاحیت موجود ہے۔",
    "میری زندگی کا اگلا باب میرے اختیار میں ہے۔",
    "تمہاری اگلی منزل ابھی لکھی نہیں گئی",
    "تمہاری سابقہ غلطیاں آخری فیصلہ نہیں ہیں۔",
    "تمہارا حال ایک ایسی جگہ ہے جہاں تم اپنے مستقبل کی تعمیر کر رہے ہو۔",
    "آج تم سیکھنے والے ہو سکتے ہو، کل تعمیر کرنے والے، اور آنے والے وقت میں استاد۔",
    "زندگی کا سب سے خوبصورت حصہ اکثر وہ ہوتا ہے جو ابھی آنا باقی ہوتا ہے۔",
    "آخری پیغام",
    "اپنی زندگی کو کامل بنانے کی کوشش مت کرو؛ اسے بامقصد بناؤ۔",
    "ہر روز کچھ سیکھو۔ کسی کی مدد کرو۔ اپنی صحت اور سوچ کا خیال رکھو۔ اپنے رب، اپنے ضمیر اور اپنے مقصد کے سامنے سچے رہو۔",
    "تم دیر سے نہیں آئے۔",
    "تم ختم نہیں ہوئے۔",
    "تم ابھی بھی تشکیل پا رہے ہو۔",
    "اور جب تک انسان سیکھ رہا ہے، اُس کی کہانی زندہ ہے۔",
    "ہر انسان کے لیے ترقی، مقصد اور باطن کی بیداری کا سفر",
    "سیکھو → سمجھو → عمل کرو → بانٹو → ترقی کرو → روشنی بنو",
    "مصنوعی ذہانت سے تخلیق کردہ مواد — محمد نوید اسحاق"
  ]
};

// Exact Roman Hindi/Urdu DOCX blocks, in original document order.
window.MINDSET_CONTENT.roman=[
  "Ek Nayi Shuruaat Aap ke Andar Se Janam Leti Hai",
  "Apni Soch Badlo.",
  "Apni Zindagi Badlo.",
  "Aap ke khayalat aap ki zindagi ki simt tay karte hain. Yeh ek dawat hai ke kuch dair rukain, apne andar jagain, aur aage barhne ke liye zyada himmat wala rasta chunein.",
  "Apna Safar Shuru Karein ↗",
  "Ba-maani tabdeeli ke liye ek pur-sukoon jagah.",
  "Roshni ki taraf barhta hua insaan",
  "01 — Bedari",
  "01 — Andar Ki Taraf Safar",
  "Har tabdeeli ek khayal se shuru hoti hai.",
  "Aahista parhein. In alfaaz ko wahan aap se milne dein jahan aap aaj kharay hain. In safhon mein shayad aap ko koi aisa sawal mil jaye jis se aap bach rahe thay, koi bhooli hui taqat dobara nazar aa jaye, ya us zindagi ki taraf pehla chhota qadam mil jaye jise aap waqai jeena chahte hain.",
  "✦",
  "Aap ki andarooni duniya qaid khana nahin. Yeh ek nuqta-e-aaghaz hai.",
  "Mukammal Mutalea",
  "Khula Hua Zehan, Wasee Tar Zindagi",
  "70 hissay — apni raftaar se parhein",
  "Soch Badlo, Zindagi Badal Do",
  "Soch, Shaoor Aur Zindagi Ke Usool",
  "Insaan ki asal zindagi us din shuru hoti hai jab woh apni soch ki zimmedari khud qabool kar leta hai.",
  "Tum Sirf Zinda Rehne Ke Liye Paida Nahin Hue",
  "Roshan Manzil 1 / 17",
  "Apni Salahiyat Ko Pehchano",
  "Tumhari kahani mein abhi bohat kuch baqi hai. Aage barho aur apne andar maujood us taqat ko pehchano jo shayad abhi tum khud bhi poori tarah nahin dekh paaye.",
  "Ab Ek Chhota Amal",
  "Apni ek aisi salahiyat yaad karo jise tum aur zyada nikharnay ka mauqa dena chahte ho.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apni Taqat Daryaft Karo →",
  "Tum is duniya mein sirf rozi kamane, logon ko khush karne, ya mushkil din guzarne ke liye nahin aaye.",
  "Tumhare andar aisi salahiyatein maujood hain jo abhi poori tarah zahir nahin hui. Tum seekh sakte ho. Tum badal sakte ho. Tum takhleeq kar sakte ho. Tum kisi doosre insaan ki zindagi ko thora sa behtar bana sakte ho.",
  "Tumhari umar tumhari kahani ka ikhtitam nahin. Yeh tumhare tajurbe, shaoor, samajh aur us taqat ka saboot hai jo tum ne saalon mein jama ki hai.",
  "Har Subah Ek Naya Faisla Hai",
  "Roshan Manzil 2 / 17",
  "Aaj Ki Subah Tumhari Hai",
  "Apni salahiyat pehchan li? Ab usay nayi simt dene ka waqt hai.",
  "Ab Ek Chhota Amal",
  "Aaj ke liye ek chhota, saaf aur waazeh faisla chuno.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Nayi Simt Ki Taraf Barho →",
  "Kal tum jo thay, aaj wahi rehna zaroori nahin.",
  "Har subah tumhare saamne do rastay khulte hain:",
  "Wohi purani soch dohrate raho jo tumhein peeche rok kar rakhti hai;",
  "ya phir apni zindagi ko ek nayi simt do.",
  "Roshan Manzil 3 / 17",
  "Faislay Se Rasta Banta Hai",
  "Ek sacha aur durust faisla tumhare liye naya darwaza khol sakta hai. Ab khauf ko ek naye andaaz se dekhne ka waqt hai.",
  "Ab Ek Chhota Amal",
  "Socho, kaunsi purani aadat ke badle tum ek behtar intekhab kar sakte ho?",
  "Yeh Qadam Mera Azm Hai ✓",
  "Khauf Ke Paar Dekho →",
  "Tabdeeli aksar ek hi din mein mukammal nahin hoti.",
  "Lekin kisi ek din kiya gaya ek sachcha faisla poori zindagi ki simt badal sakta hai.",
  "Khauf Tumhara Dushman Nahin",
  "Khauf aksar us darwaze ke bahar khara hota hai jiske andar tumhari taraqqi tumhara intezar kar rahi hoti hai.",
  "Khauf ka matlab hamesha yeh nahin hota:",
  "“Ruk jao.”",
  "Kabhi kabhi khauf sirf itna keh raha hota hai:",
  "Tum apni purani hudood se bahar nikal rahe ho.",
  "Roshan Manzil 4 / 17",
  "Khauf Ke Saath Bhi Qadam Uthao",
  "Himmat ka aaghaz us waqt bhi ho sakta hai jab yaqeen abhi poora na ho. Aage dekho ke amal kis tarah dheere dheere khud aitmaadi paida karta hai.",
  "Ab Ek Chhota Amal",
  "Apne khauf ke bawajood ek aisa chhota qadam socho jo tum aaj utha sakte ho.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Pehla Qadam Pehchano →",
  "Tum apni un purani hudood se bahar nikal rahe ho jinhein kabhi tum ne permanent samajh liya tha.",
  "Ek chhota qadam uthao.",
  "Phir doosra.",
  "Khud aitmaadi hamesha amal se pehle nahin aati.",
  "Bohat dafa khud aitmaadi is liye paida hoti hai kyun ke tum ne darr ke bawajood amal kar diya.",
  "Seekhna Umar Ka Paband Nahin",
  "Jo insaan seekhna chhor deta hai, us ke andar kuch dheere dheere rukne lagta hai.",
  "Roshan Manzil 5 / 17",
  "Tum Ab Bhi Seekh Sakte Ho",
  "Qadam uthane ki himmat, seekhne ki taqat ban sakti hai.",
  "Ab Ek Chhota Amal",
  "Ek nayi cheez chuno jise tum aaj sirf das minute de sakte ho.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Seekhne Ki Roshni Barhao →",
  "Nayi zaban, nayi maharat, nayi technology, ya duniya ko dekhne ka naya tareeqa zehan ko zinda rakhta hai.",
  "Har roz apne aap se poochho:",
  "Aaj main kal se behtar kya samajh sakta hoon?",
  "Ilm us waqt taqat banta hai jab woh sirf zehan mein na rahe, balki amal ke zariye zindagi mein utar aaye.",
  "Roshan Manzil 6 / 17",
  "Ilm Ko Zindagi Mein Utaro",
  "Samajh barh rahi hai. Ab usay apne tajurbe aur amal ki taqat se joro.",
  "Ab Ek Chhota Amal",
  "Aaj seekhi hui ek baat ko socho. Tum use kahan istemal kar sakte ho?",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apne Tajurbe Ki Taqat Dekho →",
  "Apni Takleef Ko Apni Taqat Banao",
  "Zindagi ke mushkil tajurbe tumhein sirf torne ke liye nahin aaye.",
  "Unhon ne tumhari gehraai banayi.",
  "Tumhein samajh di.",
  "Tumhein sabr diya.",
  "Aur tumhare andar woh taqat paida ki jo shayad aasaan zindagi kabhi na de pati.",
  "Jo insaan dard ko samajhta hai, woh doosron ko zyada narmi se samajh sakta hai.",
  "Jo mushkil se guzra ho, woh sabr ki asal qeemat jaanta hai.",
  "Apni kahani se sharminda mat ho.",
  "Mumkin hai tumhari zindagi ka wahi safha jise tum chhupana chahte ho, kisi din kisi aur insaan ke liye roshni ban jaye.",
  "Roshan Manzil 7 / 17",
  "Tumhari Kahani Roshni Ban Sakti Hai",
  "Apni gehraai ko pehchano. Ab is taqat ko maqsad se jorne ka waqt hai.",
  "Ab Ek Chhota Amal",
  "Apni zindagi ke kisi ek mushkil tajurbe ko yaad karo aur socho:",
  "Us ne tumhein kya sikhaya?",
  "Yeh Qadam Mera Azm Hai ✓",
  "Maqsad Ki Taraf Barho →",
  "Maqsad Milta Nahin, Banaya Jata Hai",
  "Zindagi ka maqsad hamesha aasman se kisi wazeh jawab ki surat mein nahin utarta.",
  "Maqsad dheere dheere tab banta hai jab tum:",
  "kisi maslay ko hal karte ho;",
  "kisi insaan ki mushkil aasaan karte ho;",
  "apni salahiyat ko barhate ho;",
  "jo seekhte ho woh doosron tak pohanchate ho;",
  "aur apne kaam mein imandari, khuloos aur maani paida karte ho.",
  "Roshan Manzil 8 / 17",
  "Maqsad Ek Amal Se Shuru Hota Hai",
  "Kabhi kisi ek insaan ki chhoti si mushkil aasaan karna hi ek ba-maani safar ka aaghaz ban jata hai.",
  "Ab Ek Chhota Amal",
  "Socho, tum aaj kis insaan ki ek chhoti si mushkil aasaan kar sakte ho?",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apni Salahiyat Ko Khidmat Banao →",
  "Kisi ki madad karna;",
  "apni salahiyat ko taraqqi dena;",
  "apna ilm share karna;",
  "apne kaam mein diyanat, khuloos aur maani lana—",
  "yeh sab maqsad ko janam dete hain.",
  "Roshan Manzil 9 / 17",
  "Jo Jaante Ho, Use Baanto",
  "Tumhara ilm sirf tumhara rehne ke liye nahin.",
  "Woh kisi doosre insaan ke liye faida ban sakta hai.",
  "Ab apni asal qadar ko pehchano.",
  "Ab Ek Chhota Amal",
  "Ek aisi baat chuno jo tum jaante ho aur jo kisi doosre insaan ke kaam aa sakti hai.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apni Asal Qadar Pehchano →",
  "Maqsad ka ek bohat saada usool hai:",
  "Jo kuch tum seekh rahe ho, use kisi aur ke faide ke liye istemal karo.",
  "Tumhari Qadar Sirf Aamdani Nahin",
  "Tumhari qadar tumhari tankhwah, degree, ohday ya muashrati haisiyat se bohat zyada hai.",
  "Roshan Manzil 10 / 17",
  "Tumhari Qadar Tumhare Andar Hai",
  "Tumhara kirdar, tumhari hamdardi aur tumhara tajurba tumhari taqat hain. Ab inhein rozmarrah amal mein jagah do.",
  "Ab Ek Chhota Amal",
  "Apni ek aisi khoobi yaad karo jise koi tankhwah, koi ohda aur koi hisaab poori tarah naap nahin sakta.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apni Taqat Ko Tasalsul Do →",
  "Tumhari asal qadar tumhari niyyat mein hai.",
  "Tumhare kirdar mein hai.",
  "Tumhare tajurbe mein hai.",
  "Tumhari hamdardi mein hai.",
  "Aur us bhalaai mein hai jo tum doosron ki zindagi mein le kar aate ho.",
  "Daulat zaroori hai.",
  "Lekin daulat kabhi kisi insaan ka poora taaruf nahin ban sakti.",
  "Pabandi, Josh Se Zyada Taqatwar Hai",
  "Josh aata hai.",
  "Josh chala jata hai.",
  "Kabhi dil karta hai.",
  "Kabhi nahin karta.",
  "Roshan Manzil 11 / 17",
  "Josh Se Aage, Musalsal Qadam",
  "Ab apne maqsad ko aadat ka sahara do. Kyun ke zindagi sirf un dinon par nahin chalti jab dil bohat motivated ho.",
  "Ab Ek Chhota Amal",
  "Apne maqsad ke liye roz ka ek haqeeqi aur mumkin waqt tay karo.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apni Aadat Banao →",
  "Pabandi kehti hai:",
  "Main perfect mood ka intezar nahin karunga. Main apne maqsad ki taraf qadam uthata rahunga.",
  "Har roz apne mustaqbil ko kuch waqt do.",
  "Ek ghanta ho to ek ghanta.",
  "Das minute hon to das minute.",
  "Qadam chhota ho sakta hai.",
  "Taraqqi khamosh ho sakti hai.",
  "Lekin chhote qadam jab sabr aur tasalsul se dohraye jate hain, to woh ek din us zindagi ko mumkin bana dete hain jo kabhi door khwab lagti thi.",
  "Apni Soch Ki Hifazat Karo",
  "Roshan Manzil 12 / 17",
  "Chhote Qadam, Barhti Hui Taqat",
  "Tasalsul rasta banata hai.",
  "Lekin us raste par chalne ke liye apne zehan ki hifazat bhi zaroori hai.",
  "Ab Ek Chhota Amal",
  "Kal dobara karne ke liye ek chhota sa amal tay karo.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apni Soch Ki Hifazat Karo →",
  "Jo kuch tum roz dekhte ho;",
  "jo sunte ho;",
  "jo parhte ho;",
  "aur jo baar baar apne aap se kehte ho—",
  "yeh sab mil kar tumhari andarooni duniya banate hain.",
  "Har manfi awaaz ko apne andar ghar mat do.",
  "Apne aap se usi narmi se baat karo jis narmi se tum kisi pyare dost se baat karte.",
  "Kaho:",
  "Main seekh sakta hoon.",
  "Roshan Manzil 13 / 17",
  "Apne Andar Meherban Awaaz Jagao",
  "Tumhari apni awaaz tumhari dushman bhi ban sakti hai aur tumhara sahara bhi.",
  "Use apna sahara banao.",
  "Ab Ek Chhota Amal",
  "Apne aap se kaho:",
  "Main seekh sakta hoon. Main dobara shuru kar sakta hoon.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apne Agle Baab Ki Taraf Barho →",
  "Main dobara aaghaz kar sakta hoon.",
  "Mere andar ab bhi salahiyat maujood hai.",
  "Meri zindagi ka agla baab abhi likha nahin gaya.",
  "Tumhari Agli Manzil Abhi Likhi Nahin Gayi",
  "Roshan Manzil 14 / 17",
  "Agla Baab Tumhare Ikhtiyar Mein Hai",
  "Mazi se seekh kar aaj ek nayi tameer shuru ki ja sakti hai.",
  "Ab Ek Chhota Amal",
  "Aaj ek aisa intekhab socho jis par kal ka tum fakhr kar sake.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apne Mustaqbil Ko Jagah Do →",
  "Tumhari guzri hui ghaltiyan tumhare khilaf aakhri faisla nahin hain.",
  "Tumhara haal woh jagah hai jahan tum apne mustaqbil ki buniyad rakh rahe ho.",
  "Aaj tum seekhne wale ho sakte ho.",
  "Kal tameer karne wale.",
  "Aur ek din shayad aise ustad jo apne tajurbe se kisi aur ko himmat de.",
  "Zindagi ka sab se khoobsurat hissa aksar woh hota hai jo abhi aana baqi hota hai.",
  "Roshan Manzil 15 / 17",
  "Tumhari Manzil Abhi Baqi Hai",
  "Seekhne se tameer.",
  "Tameer se khidmat.",
  "Khidmat se kisi aur ko himmat.",
  "Safar yahan rukta nahin.",
  "Ab Ek Chhota Amal",
  "Socho:",
  "Tumhari taraqqi se kis doosre insaan ko faida ho sakta hai?",
  "Yeh Qadam Mera Azm Hai ✓",
  "Maani Ki Taraf Barho →",
  "Aakhri Paigham",
  "Apni poori zindagi har cheez ko perfect banane mein mat laga do.",
  "Use ba-maqsad banao.",
  "Har roz kuch seekho.",
  "Jab mumkin ho kisi ki madad karo.",
  "Apni sehat ka khayal rakho.",
  "Apne zehan ka khayal rakho.",
  "Apne andar ke sukoon ki hifazat karo.",
  "Apne Rab ke saamne sachche raho.",
  "Apne zameer ke saamne sachche raho.",
  "Aur us maqsad ke saamne sachche raho jo tumhare andar amanat ki tarah rakha gaya hai.",
  "Tum dair se nahin aaye.",
  "Roshan Manzil 16 / 17",
  "Perfect Hone Se Pehle Ba-Maqsad Bano",
  "Ab jo kuch parha hai uski roshni ko zindagi ke ek haqeeqi amal mein le jao.",
  "Ab Ek Chhota Amal",
  "Aaj ke liye ek amal chuno:",
  "seekhna,",
  "khidmat,",
  "ya apni sehat aur andarooni sukoon ka khayal.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Aakhri Paigham Dil Se Parho →",
  "Tum khatam nahin hue.",
  "Tum abhi bhi ban rahe ho.",
  "Abhi bhi seekh rahe ho.",
  "Abhi bhi badal rahe ho.",
  "Abhi bhi tumhare andar kuch naya janam le sakta hai.",
  "Aur jab tak insaan seekhne ke liye tayyar hai, uski kahani zinda hai.",
  "Har Insaan Ke Liye Taraqqi, Maqsad Aur Baatin Ki Bedari Ka Safar",
  "Seekho → Samjho → Amal Karo → Baanto → Taraqqi Karo → Roshni Bano",
  "Masnooi Zehant Se Takhleeq Kardah Mawad — Muhammad Naveed Ishaque",
  "Roshan Manzil 17 / 17",
  "Ab Roshni Aage Barhao",
  "Tumhara chuna hua chhota amal is safar ko sirf alfaaz tak mehdood rehne se bacha sakta hai.",
  "Use zindagi mein le jao.",
  "Ab Ek Chhota Amal",
  "Pehla qadam aaj uthao.",
  "Aur kal use dobara ek mauqa do.",
  "Yeh Qadam Mera Azm Hai ✓",
  "Apne Azm Ko Taaza Karo →",
  "Agla Baab Aap Ka Hai",
  "Aap ko nayi zindagi ki zaroorat nahin.",
  "Aap ko ek nayi nazar ki zaroorat hai.",
  "Ibtida Ki Taraf Wapas Jayein ↑",
  "mindset.detleng",
  "Masnooi zehant se takhleeq kardah mawad — Muhammad Naveed Ishaque",
  "© 2026 · Mukhtalif Sochne Ki Ek Jagah"
];
